kind = "mobile"
previewPath = "/"
title = "Khrono"
version = "1.0.0"
id = "artifacts/khrono"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22861

[services.development]
run = "pnpm --filter @workspace/khrono run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/khrono", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/khrono", "run", "serve" ]

[services.env]
PORT = "22861"
BASE_PATH = "/"
