// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/contract-detail/CardExpandido.tsx": () => import("../components/mockups/contract-detail/CardExpandido.tsx"),
  "./components/mockups/contract-detail/HeroImersivo.tsx": () => import("../components/mockups/contract-detail/HeroImersivo.tsx")
};
